import gzip
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

import requests
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from loguru import logger

from app.core.config.settings import Settings


@dataclass(frozen=True)
class RemoteBackupResult:
    enabled: bool
    configured: bool
    status: str
    message: str
    asset_name: str | None = None
    uploaded_at: datetime | None = None


class GithubBackupClient:
    def __init__(self, settings: Settings) -> None:
        self._settings = settings

    def upload_encrypted_backup(self, backup_path: Path) -> RemoteBackupResult:
        if not self._settings.github_backup_enabled:
            return RemoteBackupResult(
                enabled=False,
                configured=self._is_configured(),
                status="disabled",
                message="GitHub remote backup is disabled.",
            )
        if not self._is_configured():
            return RemoteBackupResult(
                enabled=True,
                configured=False,
                status="missing_config",
                message="GitHub remote backup requires repo, token, and encryption passphrase.",
            )

        asset_name, encrypted_payload = self._build_encrypted_payload(backup_path)
        release_id = self._ensure_release()
        self._upload_asset(release_id=release_id, asset_name=asset_name, payload=encrypted_payload)
        logger.info("Encrypted GitHub backup uploaded: {}", asset_name)
        return RemoteBackupResult(
            enabled=True,
            configured=True,
            status="success",
            message=f"Uploaded encrypted backup: {asset_name}",
            asset_name=asset_name,
            uploaded_at=datetime.now(),
        )

    def status(self) -> dict[str, object]:
        return {
            "enabled": self._settings.github_backup_enabled,
            "configured": self._is_configured(),
            "repo": self._settings.github_backup_repo,
            "release_tag": self._settings.github_backup_release_tag,
        }

    def _is_configured(self) -> bool:
        return all(
            [
                self._settings.github_backup_repo,
                self._settings.github_backup_token,
                self._settings.github_backup_encryption_passphrase,
            ]
        )

    def _build_encrypted_payload(self, backup_path: Path) -> tuple[str, bytes]:
        compressed_payload = gzip.compress(backup_path.read_bytes(), compresslevel=9)
        salt = os.urandom(16)
        nonce = os.urandom(12)
        key = self._derive_key(salt)
        encrypted = AESGCM(key).encrypt(nonce, compressed_payload, backup_path.name.encode("utf-8"))
        envelope = b"HAPBK1" + salt + nonce + encrypted
        asset_name = f"{backup_path.stem}.db.gz.enc"
        return asset_name, envelope

    def _derive_key(self, salt: bytes) -> bytes:
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=390000,
        )
        return kdf.derive(self._settings.github_backup_encryption_passphrase.encode("utf-8"))

    def _ensure_release(self) -> int:
        release = self._request(
            "GET",
            f"https://api.github.com/repos/{self._settings.github_backup_repo}/releases/tags/"
            f"{self._settings.github_backup_release_tag}",
            expected_statuses={200, 404},
        )
        if release.status_code == 200:
            return int(release.json()["id"])

        created = self._request(
            "POST",
            f"https://api.github.com/repos/{self._settings.github_backup_repo}/releases",
            json={
                "tag_name": self._settings.github_backup_release_tag,
                "name": "HAP encrypted backups",
                "body": "Encrypted database backup assets generated by Home Analytics Platform.",
                "draft": False,
                "prerelease": False,
            },
            expected_statuses={201},
        )
        return int(created.json()["id"])

    def _upload_asset(self, release_id: int, asset_name: str, payload: bytes) -> None:
        encoded_name = quote(asset_name)
        self._request(
            "POST",
            f"https://uploads.github.com/repos/{self._settings.github_backup_repo}/releases/"
            f"{release_id}/assets?name={encoded_name}",
            data=payload,
            headers={"Content-Type": "application/octet-stream"},
            expected_statuses={201},
        )

    def _request(
        self,
        method: str,
        url: str,
        expected_statuses: set[int],
        **kwargs: object,
    ) -> requests.Response:
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self._settings.github_backup_token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        headers.update(kwargs.pop("headers", {}))
        response = requests.request(
            method=method,
            url=url,
            headers=headers,
            timeout=self._settings.github_backup_timeout_seconds,
            **kwargs,
        )
        if response.status_code not in expected_statuses:
            message = _extract_github_error(response)
            raise RuntimeError(f"GitHub backup request failed: {response.status_code} {message}")
        return response


def _extract_github_error(response: requests.Response) -> str:
    try:
        payload = response.json()
        message = payload.get("message")
        if isinstance(message, str):
            return message
    except ValueError:
        pass
    return response.text[:300]
